- name: variables to print
  hosts: web
  vars: #play level, all tasks in this play have access to this
    Designation:  "Hybrid Cloud DevSecOps Associate Architect"
    Prepared: "30 Days"
    Location: "Bengalore"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg:  "Hi, I am {{Designation}}, Prepared time: {{Prepared}}, Location is: {{Location}}"

  - name: print the information again
    vars: #task level variables overrides play level
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am {{Designation}}, Prepared time: {{Prepared}}, Location is: {{Location}}"
    
  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, I am {{Designation}}, Prepared time: {{Prepared}}, Location is: {{Location}}"