- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the kranthi details
    ansible.builtin.debug:
      msg:  "Hi, I am {{Designation}}, Prepared time: {{Prepared}}, Location is: {{Location}}" 