- name: variables to print
  hosts:  web
  # vars:
  #   Designation:  "DevOps Engineer from play level"
  #   Preparation:  "30 Days"
  #   Location: "Bangalore"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: Designation
  #   prompt: Please enter the Designation name
  #   private:  false # not confidential
  tasks:
  - name: print the information
    vars:
      #Designation: "Hybrid Cloud DevSecOps  task level"
      Duration: 30 Days
      Location: "Bangalore"
    ansible.builtin.debug:
      msg:  "Hi i am {{ Designation }}"

#1. command line/ args
#2. Task level
#3. Files
#4. prompt
#5. play
#6. inventory
#7. Roles