- name: demo on filters/functions
  hosts:  local
  commection: local
  tasks:  
  - name: print the default variable
    ansible.builtin.debug:
      msg:  "Hello {{ course | default('Ansible') }}"
  
  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg:  "{{ greeting | upper }}"

    - name: convert to lower
      vars:
        greeting: "Hello Ramesh"
      ansible.builtin.debug:
        msg:  "{{ greeting | lower }}"