- name: command vs shell
  hosts:  local
  connection: local
  tasks:
  - name: execute he command
    ansible.builtin.shell: ls -lrt > /tmp/output.txt # login to the server and execute command
    # command module, just issues the command

  - name: check the process
    ansible.builtin.shell:  ps -ef | grep ssh
    register: output

  - name: check the process
    ansible.builtin.command: ps -ef | grep ssh
    register: output